CREATE DATABASE EventPlus_Moura;
GO

SELECT * FROM Usuario;

USE EventPlus_Moura;
GO

CREATE TABLE TipoUsuario(
	IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo  NVARCHAR(100) NOT NULL 
);
GO

CREATE TABLE TipoEvento(
	IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Titulo  NVARCHAR(100) NOT NULL 
);
GO

CREATE TABLE Instituicao(
	IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Endereco  NVARCHAR(100) NOT NULL,
	NomeFantasia  NVARCHAR(100) NOT NULL,
	CNPJ  NVARCHAR(14) NOT NULL UNIQUE
);
GO

CREATE TABLE Usuario(
	IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Email  NVARCHAR(100) NOT NULL UNIQUE,
	Senha  NVARCHAR(256) NOT NULL UNIQUE,
	Nome  NVARCHAR(100) NOT NULL,
	IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);
GO

CREATE TABLE Evento(
	IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Descricao  TEXT NOT NULL,
	DataEvento  DATETIME NOT NULL,
	Nome  NVARCHAR(100) NOT NULL,
	IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento (IdTipoEvento),
	IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao (IdInstituicao)
);
GO

CREATE TABLE Presenca(
	IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	Situacao  BIT NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento (IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO

CREATE TABLE ComentarioEvento(
	IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
	DataComentarioEvento  DATETIME NOT NULL,
	Descricao  NVARCHAR NOT NULL,
	Exibe VARCHAR NOT NULL,
	IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento (IdEvento),
	IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario (IdUsuario)
);
GO
