CREATE DATABASE ConnectPlus;
USE ConnectPlus;


CREATE TABLE TipoContato (
 IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
 Titulo VARCHAR(100) NOT NULL
);

GO
SELECT * FROM TipoContato;

CREATE TABLE Contato (
    IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(150) NOT NULL,
    DadosContato VARCHAR(150) NOT NULL,
    Imagem VARCHAR(255),

    IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
 );

 GO

 DROP TABLE TipoContato;